music/urls.py
from django.urls import path
from . import views

app_name='music'
urlpatterns = [
    #/music/
    path('', views.IndexView.as_view(),name='index'),
    #/music/album.id/
    path('<int:pk>/',views.DetailView.as_view(),name='detail'),
]

website/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('music.urls')),
]

music/models.py
from django.db import models

class Album(models.Model):
    artist=models.CharField(max_length=250)
    album=models.CharField(max_length=500)
    genre=models.CharField(max_length=100)
    album_logo=models.CharField(max_length=1000)

    def __str__(self):
        return self.album+"-"+self.artist

class Song(models.Model):
    album=models.ForeignKey(Album,on_delete=models.CASCADE)
    file_type=models.CharField(max_length=10)
    song_title=models.CharField(max_length=250)
    is_favorite=models.BooleanField(default=False)


    def __str__(self):
        return self.song_title

music/views.py
from django.views import generic
from .models import Album, Song

class IndexView(generic.ListView):
    template_name='music/index.html'
    context_object_name="all_album"
    def get_queryset(self):
        return Album.objects.all()


class DetailView(generic.DetailView):
    model=Album
    template_name='music/details.html'
    context_object_name="all_album"
    def get_queryset(self):
        return Album.objects.all()

music/templates/music/base.html
<html lang="en">
<head>
    <title>Pranoy</title>
    {% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
<link rel="stylesheet" href='https://fonts.googleapis.com/css?family=Satisfy' type="text/css">
<link rel="stylesheet" href="{% static 'music/style.css' %}"  type="text/css"/>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
        <nav class="navbar navbar-inverse">
                <div class="container-fluid">
                  <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collaspe" data-target="#topNavBar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'music:index' %}">Pranoy</a>
                  </div>
                  <div class="collapse navbar-collapse" id="topNavBar">
                      <ul class="nav navbar-nav">
                          <li class="active">
                            <a href="{% url 'music:index' %}">
                              <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;Albums
                            </a>
                            </li>
            
                      </ul>
                      <ul class="nav navbar-nav">
                            <li class="active">
                              <a href="{% url 'music:index' %}">
                                <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;Songs
                              </a>
                              </li>
              
                        </ul>
                        <form class="navbar-form navbar-left" role="search" method="get" action="#">
                            <div class="form-group">
                                <input type="text" class="form-control" name="q" value="">
                            </div>
                            <button type="submit" class="btn btn-default">Search</button>
                        </form>
                        <ul class="nav navbar-nav navbar-right">
                                <li class="active">
                                  <a href="{% url 'music:index' %}">
                                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Add Songs
                                  </a>
                                  </li>
                                  <li class="active">
                                        <a href="{% url 'music:index' %}">
                                          <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Add Songs
                                        </a>
                                    </li>
                  
                            </ul>
                  </div>
                </div>
            </nav>
{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/details.html
<!DOCTYPE html>
{% extends 'music/base.html' %}
{% block title %}Album Details{% endblock%}
{% block body %}
<img src={{ all_album.album_logo }}>

<h1>{{ all_album.album }}</h1>
<h3>{{all_album.artist}}</h3>
{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'music:detail' all_album.id %}" method="post">
    {% csrf_token %}
    {% for song in all_album.song_set.all %}
        <input type="radio" id="song{{ loop.counter }}" name="song" value="{{ song.id }}"/>
        <level for ="song{{ loop.counter }}">
            {{ song.song_title }}
            {% if song.is_favorite %}
                <img src="home/pranoy/Downloads/star-icon.png"/>
            {% endif %}
        </level><br>
    {% endfor %}
    <input type="submit" value="Favorite"/>

</form>
{% endblock %}

music/templates/music/index.html
<!DOCTYPE html>

{% extends 'music/base.html' %}
{% block body %}
<h3>Here are all my Albums:</h3>
    <ul>
    {% for album in all_album %}
    <li><a href="{% url 'music:detail' album.id %}">{{album.album}}</a> </li>
    {% endfor %}
    </ul>
{% endblock %}